// reference site https://unicode.org/emoji/charts/full-emoji-list.html
const EMOTIONS = [
  {
    id: 1,
    iconName: 'mc-grinning-face',
    unicode: 'U+1F600',
    smilyType: 'face-smiling',
  },
  {
    id: 2,
    iconName: 'mc-grinning-face-with-big-eyes',
    unicode: 'U+1F603',
    smilyType: 'face-smiling',
  },
  {
    id: 3,
    iconName: 'mc-grinning-face-with-smiling-eyes',
    unicode: 'U+1F604',
    smilyType: 'face-smiling',
  },
  {
    id: 4,
    iconName: 'mc-beaming-face-with-smiling-eyes',
    unicode: 'U+1F604',
    smilyType: 'face-smiling',
  },
  {
    id: 5,
    iconName: 'mc-grinning-squinting-face',
    unicode: 'U+1F606',
    smilyType: 'face-smiling',
  },
  {
    id: 6,
    iconName: 'mc-grinning-face-with-sweat',
    unicode: 'U+1F605',
    smilyType: 'face-smiling',
  },
  {
    id: 7,
    iconName: 'mc-rolling-on-the-floor-laughing',
    unicode: 'U+1F923',
    smilyType: 'face-smiling',
  },
  {
    id: 8,
    iconName: 'mc-face-with-tears-of-joy',
    unicode: 'U+1F602',
    smilyType: 'face-smiling',
  },
  {
    id: 9,
    iconName: 'mc-slightly-smiling-face',
    unicode: 'U+1F642',
    smilyType: 'face-smiling',
  },
  {
    id: 10,
    iconName: 'mc-upside-down-face',
    unicode: 'U+1F643',
    smilyType: 'face-smiling',
  },
  {
    id: 11,
    iconName: 'mc-winking-face',
    unicode: 'U+1F609',
    smilyType: 'face-smiling',
  },
  {
    id: 12,
    iconName: 'mc-smiling-face-with-smiling-eyes',
    unicode: 'U+1F60A',
    smilyType: 'face-smiling',
  },
  {
    id: 13,
    iconName: 'mc-smiling-face-with-halo',
    unicode: 'U+1F607',
    smilyType: 'face-smiling',
  },
  {
    id: 14,
    iconName: 'mc-smiling-face-with-hearts',
    unicode: 'U+1F970',
    smilyType: 'face-affection',
  },
  {
    id: 15,
    iconName: 'mc-smiling-face-with-heart-eyes',
    unicode: 'U+1F60D',
    smilyType: 'face-affection',
  },
  {
    id: 16,
    iconName: 'mc-star-struck',
    unicode: 'U+1F929',
    smilyType: 'face-affection',
  },
  {
    id: 17,
    iconName: 'mc-face-blowing-a-kiss',
    unicode: 'U+1F618',
    smilyType: 'face-affection',
  },
  {
    id: 18,
    iconName: 'mc-kissing-face',
    unicode: 'U+1F617',
    smilyType: 'face-affection',
  },
  {
    id: 19,
    iconName: 'mc-smiling-face',
    unicode: 'U+263A',
    smilyType: 'face-affection',
  },
  {
    id: 20,
    iconName: 'mc-kissing-face-with-closed-eyes',
    unicode: 'U+1F61A',
    smilyType: 'face-affection',
  },
  {
    id: 21,
    iconName: 'mc-kissing-face-with-smiling-eyes',
    unicode: 'U+1F619',
    smilyType: 'face-affection',
  },
  {
    id: 22,
    iconName: 'mc-smiling-face-with-tear',
    unicode: 'U+1F972',
    smilyType: 'face-affection',
  },
  {
    id: 23,
    iconName: 'mc-face-savoring-food',
    unicode: 'U+1F60B',
    smilyType: 'face-tongue',
  },
  {
    id: 24,
    iconName: 'mc-face-with-tongue',
    unicode: 'U+1F61B',
    smilyType: 'face-tongue',
  },
  {
    id: 25,
    iconName: 'mc-winking-face-with-tongue',
    unicode: 'U+1F61C',
    smilyType: 'face-tongue',
  },
  {
    id: 26,
    iconName: 'mc-zany-face',
    unicode: 'U+1F92A',
    smilyType: 'face-tongue',
  },
  {
    id: 27,
    iconName: 'mc-squinting-face-with-tongue',
    unicode: 'U+1F61D',
    smilyType: 'face-tongue',
  },
  {
    id: 28,
    iconName: 'mc-money-mouth-face',
    unicode: 'U+1F911',
    smilyType: 'face-tongue',
  },
  {
    id: 29,
    iconName: 'mc-hugging-face',
    unicode: 'U+1F917',
    smilyType: 'face-hand',
  },
  {
    id: 30,
    iconName: 'mc-face-with-hand-over-mouth',
    unicode: 'U+1F92D',
    smilyType: 'face-hand',
  },
  {
    id: 31,
    iconName: 'mc-shushing-face',
    unicode: 'U+1F92B',
    smilyType: 'face-hand',
  },
  {
    id: 32,
    iconName: 'mc-thinking-face',
    unicode: 'U+1F914',
    smilyType: 'face-hand',
  },
  {
    id: 33,
    iconName: 'mc-zipper-mouth-face',
    unicode: 'U+1F910',
    smilyType: 'face-neutral-skeptical',
  },
  {
    id: 34,
    iconName: 'mc-face-with-raised-eyebrow',
    unicode: 'U+1F928',
    smilyType: 'face-neutral-skeptical',
  },
  {
    id: 35,
    iconName: 'mc-neutral-face',
    unicode: 'U+1F610',
    smilyType: 'face-neutral-skeptical',
  },
  {
    id: 36,
    iconName: 'mc-expressionless-face',
    unicode: 'U+1F611',
    smilyType: 'face-neutral-skeptical',
  },
  {
    id: 37,
    iconName: 'mc-face-without-mouth',
    unicode: 'U+1F636',
    smilyType: 'face-neutral-skeptical',
  },
  {
    id: 38,
    iconName: 'mc-face-in-clouds',
    unicode: 'U+1F636 U+200D U+1F32B U+FE0F',
    smilyType: 'face-neutral-skeptical',
  },
  {
    id: 39,
    iconName: 'mc-smirking-face',
    unicode: 'U+1F60F',
    smilyType: 'face-neutral-skeptical',
  },
  {
    id: 40,
    iconName: 'mc-unamused-face',
    unicode: 'U+1F612',
    smilyType: 'face-neutral-skeptical',
  },
  {
    id: 41,
    iconName: 'mc-face-with-rolling-eyes',
    unicode: 'U+1F644',
    smilyType: 'face-neutral-skeptical',
  },
  {
    id: 42,
    iconName: 'mc-grimacing-face',
    unicode: 'U+1F62C',
    smilyType: 'face-neutral-skeptical',
  },
  {
    id: 43,
    iconName: 'mc-face-exhaling',
    unicode: 'U+1F62E U+200D U+1F4A8',
    smilyType: 'face-neutral-skeptical',
  },
  {
    id: 44,
    iconName: 'mc-lying-face',
    unicode: 'U+1F925',
    smilyType: 'face-neutral-skeptical',
  },
  {
    id: 45,
    iconName: 'mc-relieved-face',
    unicode: 'U+1F60C',
    smilyType: 'face-sleepy',
  },
  {
    id: 46,
    iconName: 'mc-pensive-face',
    unicode: 'U+1F614',
    smilyType: 'face-sleepy',
  },
  {
    id: 47,
    iconName: 'mc-sleepy-face',
    unicode: 'U+1F62A',
    smilyType: 'face-sleepy',
  },
  {
    id: 48,
    iconName: 'mc-drooling-face',
    unicode: 'U+1F924',
    smilyType: 'face-sleepy',
  },
  {
    id: 49,
    iconName: 'mc-sleeping-face',
    unicode: 'U+1F634',
    smilyType: 'face-sleepy',
  },
  {
    id: 50,
    iconName: 'mc-face-with-medical-mask',
    unicode: 'U+1F637',
    smilyType: 'face-unwell',
  },
  {
    id: 51,
    iconName: 'mc-face-with-thermometer',
    unicode: 'U+1F912',
    smilyType: 'face-unwell',
  },
  {
    id: 52,
    iconName: 'mc-face-with-head-bandage',
    unicode: 'U+1F915',
    smilyType: 'face-unwell',
  },
  {
    id: 53,
    iconName: 'mc-nauseated-face',
    unicode: 'U+1F922',
    smilyType: 'face-unwell',
  },
  {
    id: 54,
    iconName: 'mc-face-vomiting',
    unicode: 'U+1F92E',
    smilyType: 'face-unwell',
  },
  {
    id: 55,
    iconName: 'mc-sneezing-face',
    unicode: 'U+1F927',
    smilyType: 'face-unwell',
  },
  {
    id: 56,
    iconName: 'mc-hot-face',
    unicode: 'U+1F975',
    smilyType: 'face-unwell',
  },
  {
    id: 57,
    iconName: 'mc-cold-face',
    unicode: 'U+1F976',
    smilyType: 'face-unwell',
  },
  {
    id: 58,
    iconName: 'mc-woozy-face',
    unicode: 'U+1F974',
    smilyType: 'face-unwell',
  },
  {
    id: 59,
    iconName: 'mc-dizzy-face',
    unicode: 'U+1F635',
    smilyType: 'face-unwell',
  },
  {
    id: 60,
    iconName: 'mc-face-with-spiral-eyes',
    unicode: 'U+1F635 U+200D U+1F4AB',
    smilyType: 'face-unwell',
  },
  {
    id: 61,
    iconName: 'mc-exploding-head',
    unicode: 'U+1F92F',
    smilyType: 'face-unwell',
  },
  {
    id: 62,
    iconName: 'mc-cowboy-hat-face',
    unicode: 'U+1F920',
    smilyType: 'face-hat',
  },
  {
    id: 63,
    iconName: 'mc-partying-face',
    unicode: 'U+1F973',
    smilyType: 'face-hat',
  },
  {
    id: 64,
    iconName: 'mc-disguised-face',
    unicode: 'U+1F978',
    smilyType: 'face-hat',
  },
  {
    id: 65,
    iconName: 'mc-smiling-face-with-sunglasses',
    unicode: 'U+1F60E',
    smilyType: 'face-glasses',
  },
  {
    id: 66,
    iconName: 'mc-nerd-face',
    unicode: 'U+1F913',
    smilyType: 'face-glasses',
  },
  {
    id: 67,
    iconName: 'mc-face-with-monocle',
    unicode: 'U+1F9D0',
    smilyType: 'face-glasses',
  },
  {
    id: 68,
    iconName: 'mc-confused-face',
    unicode: 'U+1F615',
    smilyType: 'face-concerned',
  },
  {
    id: 69,
    iconName: 'mc-worried-face',
    unicode: 'U+1F61F',
    smilyType: 'face-concerned',
  },
  {
    id: 70,
    iconName: 'mc-slightly-frowning-face',
    unicode: 'U+1F641',
    smilyType: 'face-concerned',
  },
  {
    id: 71,
    iconName: 'mc-frowning-face',
    unicode: 'U+2639',
    smilyType: 'face-concerned',
  },
  {
    id: 72,
    iconName: 'mc-face-with-open-mouth',
    unicode: 'U+1F62E',
    smilyType: 'face-concerned',
  },
  {
    id: 73,
    iconName: 'mc-hushed-face',
    unicode: 'U+1F62F',
    smilyType: 'face-concerned',
  },
  {
    id: 74,
    iconName: 'mc-astonished-face',
    unicode: 'U+1F632',
    smilyType: 'face-concerned',
  },
  {
    id: 75,
    iconName: 'mc-flushed-face',
    unicode: 'U+1F633',
    smilyType: 'face-concerned',
  },
  {
    id: 76,
    iconName: 'mc-pleading-face',
    unicode: 'U+1F97A',
    smilyType: 'face-concerned',
  },
  {
    id: 77,
    iconName: 'mc-frowning-face-with-open-mouth',
    unicode: 'U+1F626',
    smilyType: 'face-concerned',
  },
  {
    id: 78,
    iconName: 'mc-anguished-face',
    unicode: 'U+1F627',
    smilyType: 'face-concerned',
  },
  {
    id: 79,
    iconName: 'mc-fearful-face',
    unicode: 'U+1F628',
    smilyType: 'face-concerned',
  },
  {
    id: 80,
    iconName: 'mc-anxious-face-with-sweat',
    unicode: 'U+1F630',
    smilyType: 'face-concerned',
  },
  {
    id: 81,
    iconName: 'mc-sad-but-relieved-face',
    unicode: 'U+1F625',
    smilyType: 'face-concerned',
  },
  {
    id: 82,
    iconName: 'mc-crying-face',
    unicode: 'U+1F622',
    smilyType: 'face-concerned',
  },
  {
    id: 83,
    iconName: 'mc-loudly-crying-face',
    unicode: 'U+1F62D',
    smilyType: 'face-concerned',
  },
  {
    id: 84,
    iconName: 'mc-face-screaming-in-fear',
    unicode: 'U+1F631',
    smilyType: 'face-concerned',
  },
  {
    id: 85,
    iconName: 'mc-confounded-face',
    unicode: 'U+1F616',
    smilyType: 'face-concerned',
  },
  {
    id: 86,
    iconName: 'mc-persevering-face',
    unicode: 'U+1F623',
    smilyType: 'face-concerned',
  },
  {
    id: 87,
    iconName: 'mc-disappointed-face',
    unicode: 'U+1F61E',
    smilyType: 'face-concerned',
  },
  {
    id: 88,
    iconName: 'mc-downcast-face-with-sweat',
    unicode: 'U+1F613',
    smilyType: 'face-concerned',
  },
  {
    id: 89,
    iconName: 'mc-weary-face',
    unicode: 'U+1F629',
    smilyType: 'face-concerned',
  },
  {
    id: 90,
    iconName: 'mc-tired-face',
    unicode: 'U+1F62B',
    smilyType: 'face-concerned',
  },
  {
    id: 91,
    iconName: 'mc-yawning-face',
    unicode: 'U+1F971',
    smilyType: 'face-concerned',
  },
  {
    id: 92,
    iconName: 'mc-face-with-steam-from-nose',
    unicode: 'U+1F624',
    smilyType: 'face-negative',
  },
  {
    id: 93,
    iconName: 'mc-pouting-face',
    unicode: 'U+1F621',
    smilyType: 'face-negative',
  },
  {
    id: 94,
    iconName: 'mc-angry-face',
    unicode: 'U+1F620',
    smilyType: 'face-negative',
  },
  {
    id: 95,
    iconName: 'mc-face-with-symbols-on-mouth',
    unicode: 'U+1F92C',
    smilyType: 'face-negative',
  },
  {
    id: 96,
    iconName: 'mc-smiling-face-with-horns',
    unicode: 'U+1F608',
    smilyType: 'face-negative',
  },
  {
    id: 97,
    iconName: 'mc-angry-face-with-horns',
    unicode: 'U+1F47F',
    smilyType: 'face-negative',
  },
]
